name: Deploy JupyterLite App

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Google credentials (from .txt file stored in secrets)
      - name: Set up Google credentials
        run: |
          echo "${{ secrets.GOOGLE_SHEET_CREDENTIALS }}" > google_sheet_credentials.txt
        env:
          GOOGLE_SHEET_CREDENTIALS: ${{ secrets.GOOGLE_SHEET_CREDENTIALS }}

      # Step 3: Set up Zoom credentials and other environment variables
      - name: Set up Zoom and other environment variables
        run: |
          echo "ZOOM_ACCOUNT_ID=${{ secrets.ZOOM_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "ZOOM_CLIENT_ID=${{ secrets.ZOOM_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ZOOM_CLIENT_SECRET=${{ secrets.ZOOM_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ZOOM_TOKEN_URL=${{ secrets.ZOOM_TOKEN_URL }}" >> $GITHUB_ENV
          echo "SENDER_EMAIL=${{ secrets.SENDER_EMAIL }}" >> $GITHUB_ENV
          echo "SENDER_PASSWORD=${{ secrets.SENDER_PASSWORD }}" >> $GITHUB_ENV
          echo "SHEET_ID=${{ secrets.SHEET_ID }}" >> $GITHUB_ENV

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          pip install voici  # Install Voici (used instead of Voilà)

      # Step 5: Build and deploy JupyterLite app
      - name: Build and deploy JupyterLite app
        run: |
          voici build --output-dir _output --contents CaseBud_fin.ipynb --lite-dir .
          voici export --output-archive CaseBud-jupyterlite.tgz

      # Step 6: Upload _output to GitHub Pages
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r _output/* .
          git add .
          git commit -m "Deploy JupyterLite App"
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gh-pages



