name: Deploy JupyterLite App

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the main branch
  pull_request:
    branches:
      - '*'  # Trigger on any pull request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.8-0'
          environment-file: 'build-environment.yml'

      - name: Set up Google credentials
        run: echo "${{ secrets.GOOGLE_SHEET_CREDENTIALS }}" > google_sheet_credentials.txt
        env:
          GOOGLE_SHEET_CREDENTIALS: ${{ secrets.GOOGLE_SHEET_CREDENTIALS }}

      - name: Set up environment variables
        run: |
          for var in ZOOM_ACCOUNT_ID ZOOM_CLIENT_ID ZOOM_CLIENT_SECRET ZOOM_TOKEN_URL SENDER_EMAIL SENDER_PASSWORD SHEET_ID; do
            echo "$var=${{ secrets[var] }}" >> $GITHUB_ENV
          done

      - name: Install Voici and JupyterLite dependencies
        run: pip install voici jupyterlite jupyterlite-xeus

      - name: Build JupyterLite App
        shell: bash -l {0}
        run: voici build --output-dir dist --content content --lite-dir . --XeusKernelApp.environment_file=build-environment.yml


      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
